In [1]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv('hair_loss.csv')
print(df.head())

   total_protein  total_keratine  hair_texture  vitamin  manganese  iron  \
0            312             122            14      249         87    55   
1             52             227             3      425        387     1   
2            172             197            11      142        199    91   
3            256             334            19      358        122     3   
4            329             185            58      227        329   321   

   calcium  body_water_content  stress_level  liver_data  hair_fall  
0      333                  44            41         368          4  
1      182                  26            65          41          1  
2      414                  32            54          92          4  
3       35                  48            45          65          2  
4      345                  23            92         346          4  


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   total_protein       100000 non-null  int64
 1   total_keratine      100000 non-null  int64
 2   hair_texture        100000 non-null  int64
 3   vitamin             100000 non-null  int64
 4   manganese           100000 non-null  int64
 5   iron                100000 non-null  int64
 6   calcium             100000 non-null  int64
 7   body_water_content  100000 non-null  int64
 8   stress_level        100000 non-null  int64
 9   liver_data          100000 non-null  int64
 10  hair_fall           100000 non-null  int64
dtypes: int64(11)
memory usage: 8.4 MB


In [4]:
df.isnull().sum()

total_protein         0
total_keratine        0
hair_texture          0
vitamin               0
manganese             0
iron                  0
calcium               0
body_water_content    0
stress_level          0
liver_data            0
hair_fall             0
dtype: int64

In [5]:
df_drop = df.drop([], axis=1)

In [6]:
df_new = df_drop.dropna()

In [7]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   total_protein       100000 non-null  int64
 1   total_keratine      100000 non-null  int64
 2   hair_texture        100000 non-null  int64
 3   vitamin             100000 non-null  int64
 4   manganese           100000 non-null  int64
 5   iron                100000 non-null  int64
 6   calcium             100000 non-null  int64
 7   body_water_content  100000 non-null  int64
 8   stress_level        100000 non-null  int64
 9   liver_data          100000 non-null  int64
 10  hair_fall           100000 non-null  int64
dtypes: int64(11)
memory usage: 8.4 MB


In [8]:
X = df_new.drop('hair_fall', axis=1).values
y = df_new['hair_fall'].values

In [9]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Define the model using TensorFlow and Keras
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, activation='sigmoid', input_shape=(10,))
])

In [11]:
# Compile the model
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [12]:
# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=10, verbose=1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print("Accuracy:", accuracy)

Epoch 1/10
8000/8000 [==============================] - 6s 730us/step - loss: -13972.2334 - accuracy: 0.1665
Epoch 2/10
8000/8000 [==============================] - 6s 757us/step - loss: -40568.5469 - accuracy: 0.1665
Epoch 3/10
8000/8000 [==============================] - 6s 788us/step - loss: -67181.9297 - accuracy: 0.1665
Epoch 4/10
8000/8000 [==============================] - 6s 749us/step - loss: -93808.7734 - accuracy: 0.1665
Epoch 5/10
8000/8000 [==============================] - 6s 709us/step - loss: -120395.5859 - accuracy: 0.1665
Epoch 6/10
8000/8000 [==============================] - 6s 705us/step - loss: -146989.0938 - accuracy: 0.1665
Epoch 7/10
8000/8000 [==============================] - 6s 760us/step - loss: -173570.9375 - accuracy: 0.1665
Epoch 8/10
8000/8000 [==============================] - 6s 763us/step - loss: -200146.3594 - accuracy: 0.1665
Epoch 9/10
8000/8000 [==============================] - 6s 718us/step - loss: -226779.1406 - accuracy: 0.1665
Epoch 10/10
62

In [13]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

625/625 [==============================] - 0s 673us/step


In [14]:
# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Perceptron Confusion Matrix:
 [[3317    0    0    0    0]
 [6644    0    0    0    0]
 [3328    0    0    0    0]
 [3345    0    0    0    0]
 [3366    0    0    0    0]]
